# GitLab CI configuration using ci-templates

include:
  - project: 'dessia/sdk/ci-templates'
    file: '/templates/common.yml'
  - project: 'dessia/sdk/ci-templates'
    file: '/templates/verify_changelog.yml'
  - project: 'dessia/sdk/ci-templates'
    file: '/templates/check_pre_commit.yml'
  - project: 'dessia/sdk/ci-templates'
    file: '/templates/install_test.yml'
  - project: 'dessia/sdk/ci-templates'
    file: '/templates/generate_dist_wheel.yml'


verify_changelog_update:
  extends: .verify_changelog


check_pre_commit:
  extends: .check_pre_commit


install_run_scripts_and_unittests:
  extends: .install_test
  variables:
    INSTALL_GROUPS: "test"


generate_dist_wheel:
  extends: .generate_dist_wheel
