# This file configures automated checks triggered by git events.
# To install pre-commit, run: `pip install pre-commit`
#
# To run all hooks manually, use: `pre-commit run -a`
# To enable automated checks on commit, run: `pre-commit install`
#
# See https://github.com/pre-commit/pre-commit for more information

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, "black", --line-length, "120"]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [-l, "120"]
        language_version: python3.9

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=50']
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-symlinks

  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
